// apps/client/src/services/import.ts
// Thin typed wrapper for the media_import command.
//
// The bindings under `../bindings` are generated by tauri-specta at build time
// and checked in. This module adds a stable import path and re-exports the
// `ImportedMedia` return type so the rest of the app does not need to know
// the bindings directory layout.

import { commands } from "./ipc";

export type ImportedMedia = Awaited<
  ReturnType<typeof commands.mediaImport>
>[number];

export async function mediaImport(paths: string[]): Promise<ImportedMedia[]> {
  return commands.mediaImport(paths);
}
