// apps/client/src/services/ipc.ts
// Thin typed wrapper over the Rust IPC surface.
//
// The bindings under `../bindings` are generated by tauri-specta at build time
// and checked in. Do not edit them; instead, re-export their public surface
// from this module so the rest of the app has a single, stable import path
// for IPC.

export { commands, events } from "../bindings";
export type Commands = typeof import("../bindings").commands;
export type GreetResult = Awaited<ReturnType<typeof import("../bindings").commands.greet>>;
