// apps/client/src/services/quota.ts
// Thin typed wrapper for the disk-quota Tauri commands.
//
// The bindings under `../bindings` are generated by tauri-specta at
// build time and checked in. This module adds a stable import path
// and re-exports the `QuotaInfo` return type so the rest of the app
// does not need to know the bindings directory layout.

import { commands } from "./ipc";
import type { QuotaInfo } from "../bindings";

export type { QuotaInfo };

export async function getQuota(): Promise<QuotaInfo> {
  return commands.quotaGet();
}

export async function setQuota(newCapBytes: number): Promise<void> {
  return commands.quotaSet(newCapBytes);
}
