// apps/client/src/services/scan.ts
// Thin typed wrapper for the `library_scan` Tauri command.
//
// The bindings under `../bindings` are generated by tauri-specta at
// build time and checked in. This module adds a stable import path
// and re-exports the `ScanResult` return type so the rest of the app
// does not need to know the bindings directory layout.

import { commands } from "./ipc";
import type { ScanResult } from "../bindings";

export type { ScanResult };

export async function libraryScan(): Promise<ScanResult> {
  return commands.libraryScan();
}
