// ESLint flat config for the Locast client.
//
// Lints the whole client tree (src, tests, scripts, root configs). Only build
// output and generated files are ignored. The bindings file is generated by
// tauri-specta and checked in by hand; it is not authored code.

import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        ignores: [
            "dist/**",
            "test-results/**",
            "playwright-report/**",
            "perf-results/**",
            "src-tauri/**",
            "src/bindings/**",
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        linterOptions: { reportUnusedDisableDirectives: "error" },
        languageOptions: {
            globals: { ...globals.browser, ...globals.node },
        },
        plugins: { "react-hooks": reactHooks },
        rules: {
            "react-hooks/rules-of-hooks": "error",
            "react-hooks/exhaustive-deps": "error",
            // tsc already enforces unused locals/params (noUnusedLocals,
            // noUnusedParameters); keep ESLint's copy consistent with the
            // leading-underscore convention instead of double-reporting.
            "@typescript-eslint/no-unused-vars": [
                "error",
                { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
            ],
        },
    },
    {
        // Playwright fixtures receive a `use()` callback, which the React
        // hooks rule mistakes for React's `use` hook. These files contain no
        // React code.
        files: ["tests/**"],
        rules: {
            "react-hooks/rules-of-hooks": "off",
            "react-hooks/exhaustive-deps": "off",
        },
    },
);
