//! Bindings generation for the Locast desktop client.
//!
//! P0-T06 wires up the `tauri-specta` -> TypeScript bindings pipeline.
//! This integration test:
//!
//! 1. Collects every `#[tauri::command]` declared in
//!    `locast_client_lib::commands` and every event type declared in
//!    `locast_client_lib::events` via the `tauri_specta::collect_commands!`
//!    and `tauri_specta::collect_events!` macros.
//! 2. Renders the TypeScript surface to a temporary file (the
//!    `tauri-specta` `LanguageExt` API only supports writing to a path,
//!    not rendering to a string).
//! 3. Compares the freshly generated content against the file on disk
//!    and either prints "OK: bindings already up to date" (match) or
//!    overwrites the on-disk file and panics with a clear instruction
//!    (mismatch).
//!
//! The test is marked `#[ignore]` so it does not run on every CI build;
//! invoke it manually via:
//!
//! ```text
//! cargo test -p locast-client --test gen_bindings -- --ignored
//! ```
//!
//! The CI workflow (`.github/workflows/ci.yml`) re-runs this test in
//! its `bindings-reproducibility` step and asserts that the result is a
//! no-op against the checked-in bindings file (i.e. `git diff
//! --exit-code apps/client/src/bindings/` is empty).
//!
//! ## Windows host note
//!
//! The tauri-specta collector macros depend on the full Tauri runtime,
//! which on Windows links against the wry `WebView2Loader.dll`. On hosts
//! where the bundled `WebView2Loader.dll` (1.0.3650.58, shipped with
//! tauri/wry 0.55) is incompatible with the installed Edge WebView2
//! redist (1.0.151.x+), the test binary fails to start with
//! `STATUS_ENTRYPOINT_NOT_FOUND` (0xC0000139). When that happens the
//! `tauri-specta` and `wry` teams are the right places to look; as a
//! workaround this integration test body is gated to non-Windows so
//! `cargo test --workspace` does not break for unaffected Windows
//! developers. The bindings file itself is still checked in and the
//! generation step in CI runs on Linux and macOS where wry uses
//! webkit/gtk and the loader issue does not exist.

/// Path to the generated bindings file, relative to this integration
/// test's working directory. Cargo runs integration tests with the
/// crate root as the CWD, so the bindings live at
/// `apps/client/src/bindings/index.ts` (one directory up from
/// `src-tauri/`).
#[allow(dead_code)]
const BINDINGS_PATH: &str = "../src/bindings/index.ts";

/// On Windows hosts where the wry `WebView2Loader.dll` is incompatible
/// with the installed Edge WebView2 runtime, the tauri-specta collector
/// macros cause the test binary to fail at process startup with
/// `STATUS_ENTRYPOINT_NOT_FOUND`. This stub test exists so the
/// integration test target compiles and runs cleanly on every
/// platform; see the `Windows host note` above for the full
/// explanation.
#[cfg(target_os = "windows")]
#[test]
fn windows_stub() {
    // No-op on Windows. The bindings file is committed to the repo and
    // is regenerated by CI on Linux and macOS.
}

#[cfg(not(target_os = "windows"))]
mod inner {
    use std::path::PathBuf;

    use specta_typescript::Typescript;
    use tauri::test::MockRuntime;
    use tauri_specta::{collect_commands, collect_events, Builder};

    use locast_client_lib::commands;

    /// Build the tauri-specta `Builder` for the current command and
    /// event set. Kept in a helper so the test body stays declarative
    /// and the `Builder` configuration is easy to extend in future
    /// phases.
    ///
    /// We use `tauri::test::MockRuntime` as the generic parameter so
    /// the test binary does not link against `wry`'s WebView2 runtime.
    /// The runtime is a phantom type for `tauri-specta`'s `Builder`;
    /// the generator does not need to instantiate it. MockRuntime is
    /// gated by the `tauri/test` feature which is enabled in
    /// `[dev-dependencies]`.
    pub fn build_specta() -> Builder<MockRuntime> {
        Builder::<MockRuntime>::new()
            .commands(collect_commands![
                commands::greet,
                commands::import::media_import,
                commands::quota::quota_get,
                commands::quota::quota_set,
                commands::scan::library_scan,
                commands::protocol::media_resolve_url,
                commands::identity::identity_get,
                commands::identity::identity_rotate,
                commands::identity::identity_set_display_name,
            ])
            .events(collect_events![])
            // BigInt-style integer types (i64, u64, etc.) appear
            // in the IPC surface (e.g. `ImportedMedia.size_bytes`,
            // `QuotaInfo.used_bytes`, `quota_set(new_cap_bytes)`).
            // JavaScript's `number` cannot represent the full
            // i64/u64 range losslessly, but for a desktop media
            // library the values stay well under 2^53 bytes
            // (≈ 9 PiB). We opt into the lossy export; the
            // per-field `#[specta(type =
            // specta_typescript::Number)]` annotations on the
            // structs that go over IPC are equivalent and
            // document the decision in the type definitions.
            .dangerously_cast_bigints_to_number()
    }

    /// Render the bindings into a string. Uses a temporary file
    /// because `tauri_specta::LanguageExt::export` only writes to a
    /// path.
    pub fn render_bindings() -> String {
        let tmp = tempfile::Builder::new()
            .suffix(".ts")
            .tempfile()
            .expect("create temp file for bindings render");

        let specta = build_specta();
        specta
            .export(Typescript::default(), tmp.path())
            .expect("export tauri-specta bindings to TypeScript");

        std::fs::read_to_string(tmp.path()).expect("read rendered bindings")
    }

    /// Write `rendered` to the on-disk bindings path, creating parent
    /// directories as needed.
    pub fn write_bindings(rendered: &str) {
        let path = PathBuf::from(super::BINDINGS_PATH);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create bindings directory");
        }
        std::fs::write(&path, rendered).expect("write bindings file");
    }

    /// The generator test.
    ///
    /// Ignored by default so it does not run on every `cargo test`
    /// invocation. Run with `--ignored` to regenerate the bindings.
    #[test]
    #[ignore]
    pub fn gen_bindings() {
        let rendered = render_bindings();
        let existing = std::fs::read_to_string(super::BINDINGS_PATH).ok();

        match existing {
            Some(existing) if existing == rendered => {
                println!("OK: bindings already up to date");
            }
            _ => {
                write_bindings(&rendered);
                panic!(
                    "bindings are out of date; run `cargo test -p locast-client \
                     --test gen_bindings -- --ignored` to regenerate."
                );
            }
        }
    }
}
