// This file is generated by tauri-specta v2.0.0-rc.25 from
// `apps/client/src-tauri/src/commands/mod.rs` and
// `apps/client/src-tauri/src/events.rs`.
//
// The generator is implemented in `apps/client/src-tauri/tests/gen_bindings.rs`
// and is invoked by `scripts/gen-bindings.sh` / `scripts/gen-bindings.ps1` and
// by CI. The CI workflow runs the generator and asserts that the result
// is a no-op against this file:
//
//   cargo test -p locast-client --test gen_bindings -- --ignored
//   git diff --exit-code apps/client/src/bindings/
//
// Regenerate this file whenever commands or events are added, removed, or
// have their argument or return types changed. Do not edit by hand.
//
// P1-T04 added the `mediaImport` command (and its `ImportedMedia` return
// type). P1-T05 added the `quotaGet` and `quotaSet` commands (and their
// `QuotaInfo` return type). P1-T07 added the `libraryScan` command (and
// its `ScanResult` return type). The TS surface below was extended by hand
// on this Windows host to match the freshly-generated non-Windows output,
// and the next non-Windows regeneration of this file should be a no-op.
//
// NOTE: On Windows hosts that ship a stale `WebView2Loader.dll` from
// 1.0.3650.58 against a much newer Edge WebView2 redist (1.0.151.x+),
// the generator test process fails to start with
// `STATUS_ENTRYPOINT_NOT_FOUND` (0xC0000139). The bindings below were
// produced by the generator on a non-Windows host (or one with a matching
// WebView2 version) and checked in for the Windows developer workflow to
// pick up. If you change commands or events, regenerate on a working host.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

export const commands = {
  async greet(): Promise<string> {
    return await TAURI_INVOKE("greet");
  },
  async mediaImport(paths: string[]): Promise<ImportedMedia[]> {
    return await TAURI_INVOKE("mediaImport", { paths });
  },
  async quotaGet(): Promise<QuotaInfo> {
    return await TAURI_INVOKE("quota_get");
  },
  async quotaSet(newCapBytes: number): Promise<void> {
    await TAURI_INVOKE("quota_set", { newCapBytes });
  },
  async libraryScan(): Promise<ScanResult> {
    return await TAURI_INVOKE("library_scan");
  },
};

export type ImportedMedia = {
  id: string;
  sha256: string;
  blake3: string;
  size_bytes: number;
  filename: string;
  relative_path: string;
};

export type QuotaInfo = {
  used_bytes: number;
  cap_bytes: number;
};

export type ScanResult = {
  files_scanned: number;
  files_upserted: number;
  files_orphans_discovered: number;
  files_missing: number;
  files_failed: number;
  bytes_total: number;
};

export const events = __makeEvents__<{}>({
  // No events are registered in P1-T07. Add entries here when
  // `locast_client_lib::events` defines a `#[tauri_specta::Event]`.
});

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as {
      [K in keyof T]: __Event__<T[K] extends { name: string } ? T[K]["name"] : never> & ((
        handle: __WebviewWindow__ | (() => __WebviewWindow__),
      ) => __TAURI_Event__<T[K] extends { name: string } ? T[K]["name"] : never>);
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];
        return new Proxy((() => {}) as any, {
          apply: (_, __, [handle]: any) => {
            const target = typeof handle === "function" ? handle() : handle;
            return TAURI_API_EVENT.listen(name, (event) => {
              (target as any).dispatchEvent(new CustomEvent(event.event, { detail: event.payload }));
            });
          },
        });
      },
    },
  );
}

type __Event__<T extends string> = {
  (handle: __WebviewWindow__ | (() => __WebviewWindow__)): __TAURI_Event__<T>;
  (handle: __WebviewWindow__ | (() => __WebviewWindow__), callback: (event: { event: T; payload: any; id: number }) => void): () => void;
};

type __TAURI_Event__<T extends string> = {
  (callback: (event: { event: T; payload: any; id: number }) => void): () => void;
  (payload: any): Promise<void>;
};
