// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Example payload used to smoke-test the `ts-rs` generator in P0-T07.
 *
 * This is deliberately a toy struct, not a real protocol envelope. The
 * shape exercises the bits the generator needs to round-trip:
 *
 * - a `String` (`id`) to exercise string marshalling
 * - an integer (`counter`) to exercise numeric marshalling
 * - an `Option<String>` (`note`) to exercise nullable fields
 * - a nested `enum` (`mood`) to exercise tagged-union marshalling
 *
 * `mood` is marked `#[ts(inline)]` so the `Mood` union is rendered inline
 * in `HelloWorld` and the generated `ts/index.ts` stays self-contained
 * (no `import { Mood } from "../Mood"` line). Real envelope types in P3+
 * will be free to either inline or import; this is a smoke test of the
 * generator, not a fixed design decision.
 *
 * Real envelope types land in P3+ per `docs/ARCHITECTURE.md` section 18.3.
 */
export type HelloWorld = { id: string, counter: number, note: string | null, mood: "Happy" | "Neutral" | "Sad", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Mood = "Happy" | "Neutral" | "Sad";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire envelope for every message. See §18.3.
 */
export type Envelope = { 
/**
 * Protocol version. Always `1` for v1; receivers reject
 * anything else (§18.11).
 */
v: number, 
/**
 * The message type. See [`MessageKind`]. Wire field is
 * `type`; we use a Rust field name that does not collide
 * with the reserved keyword.
 */
type: MessageKind, 
/**
 * Unique per-message UUID v7. The idempotency key for
 * server-side dedup (§18.7).
 */
id: string, 
/**
 * `None` for handshake messages; `Some(room_id)` otherwise.
 */
room_id: string | null, 
/**
 * `None` for handshake and server-originated messages.
 */
sender: Sender | null, 
/**
 * Sender wall clock at send (unix ms). Informational;
 * replay protection is by `seq` (§18.7).
 */
ts_ms: bigint, 
/**
 * Monotonic per-sender sequence. First message after
 * connect is `1`; never reused.
 */
seq: bigint, 
/**
 * Type-specific payload. Held as a generic JSON value so
 * the envelope is schema-agnostic.
 */
payload: unknown, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The message type tag. Wire field is `type`. The v1 spec only
 * defines a handful of types; future types (P3+ room lifecycle,
 * playback, drawing, etc.) will be added as new variants.
 */
export type MessageKind = "HELLO" | "WELCOME" | "CHALLENGE" | "AUTH" | "AUTH_OK" | "AUTH_FAIL" | "ROOM_CREATE" | "ROOM_CREATED" | "ROOM_JOIN_REQUEST" | "ROOM_JOINED" | "ROOM_LEAVE" | "ROOM_STATE" | "PARTICIPANT_JOINED" | "PARTICIPANT_LEFT" | "HOST_DISCONNECTED" | "HOST_RECONNECTED" | "HOST_MIGRATED" | "ROOM_CLOSED" | "ROOM_ERROR" | "PRESENCE";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The per-envelope sender identity. The signature is over the
 * canonicalized payload bytes (§18.9). The sender is `None` for
 * handshake messages and server-originated broadcasts.
 */
export type Sender = { 
/**
 * Server-assigned UUID v7 (architecture §20.4.4). The
 * client-side `user_id` (sha256 hex) is NOT used here.
 */
user_id: string, 
/**
 * 32-byte Ed25519 public key.
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the canonical payload
 * (or, for AUTH, over the raw 32-byte nonce).
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HELLO (C -> S).
 */
export type HelloPayload = { client_version: string, platform: "win" | "mac" | "linux", device_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WELCOME (S -> C).
 */
export type WelcomePayload = { session_id: string, server_ts_ms: bigint, config: WelcomeConfig, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-published session configuration.
 */
export type WelcomeConfig = { max_room_size: number, rate: WelcomeRate, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-connection rate limits announced at WELCOME.
 */
export type WelcomeRate = { msgs_per_sec: number, bytes_per_sec: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CHALLENGE (S -> C).
 */
export type ChallengePayload = { 
/**
 * 32-byte random nonce. The client signs this raw (no
 * domain tag, §20.4.4) and returns the signature in
 * [`AuthPayload::sig`].
 */
nonce: Array<number>, 
/**
 * Server-side absolute expiry (unix ms).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH (C -> S).
 */
export type AuthPayload = { 
/**
 * 32-byte Ed25519 public key. The server uses this as the
 * canonical identifier for the user (§21.3).
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the raw 32-byte nonce
 * from the preceding CHALLENGE.
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_OK (S -> C).
 */
export type AuthOkPayload = { 
/**
 * Server-assigned UUID v7 (§20.4.4). NOT the client's
 * sha256-hex `user_id`.
 */
user_id: string, bearer: AuthBearer, 
/**
 * The 32-byte public key the server associated with the
 * user. Echoes the value the client sent in AUTH so the
 * client can confirm the binding.
 */
pubkey: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bearer token issued by the server on successful AUTH.
 */
export type AuthBearer = { 
/**
 * 32-byte bearer token. The client holds the plaintext
 * only in memory; the server stores sha256(token) in
 * SQLite (§21.3).
 */
token: Array<number>, 
/**
 * Absolute expiry (unix ms). 15 minutes by default (§20.4.4).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_FAIL (S -> C).
 */
export type AuthFailPayload = { reason: "bad_sig" | "expired" | "banned" | "rate", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failure reason for an AUTH_FAIL.
 */
export type AuthFailReason = "bad_sig" | "expired" | "banned" | "rate";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The client OS. v1 supports win, mac, linux.
 */
export type Platform = "win" | "mac" | "linux";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CREATE (C -> S). The creator chooses the migration
 * setting at creation; the v1 protocol does not let it be
 * changed later.
 */
export type RoomCreatePayload = { title: string, migration_enabled: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CREATED (S -> C). Server's response to a successful
 * ROOM_CREATE. Includes the room summary and the caller's own
 * participant record.
 */
export type RoomCreatedPayload = { room: RoomSummary, you: ParticipantSelf, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_JOIN_REQUEST (C -> S). The 6-char code is uppercase; the
 * display name is 1-32 chars and validated by the server.
 */
export type RoomJoinRequestPayload = { code: string, display_name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_JOINED (S -> C). Server's response to a successful
 * ROOM_JOIN_REQUEST.
 */
export type RoomJoinedPayload = { room: RoomSummary, you: ParticipantSelf, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_LEAVE (C -> S). Intentional leave. The payload is
 * empty in v1; the server reads the authenticated user_id off
 * the bearer.
 */
export type RoomLeavePayload = Record<symbol, never>;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_STATE (S -> C). Full snapshot of a room.
 */
export type RoomStatePayload = { room: RoomSummary, 
/**
 * When the host transport has been lost and the room has
 * migration enabled, this is the unix-ms deadline after
 * which the server will elect a new host. `None` when the
 * host is connected.
 */
host_disconnect_deadline_ms: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The caller's own view of themselves in a room. Echoed in
 * `ROOM_CREATED` / `ROOM_JOINED` so the client can show the
 * right `joined_ms` / `cap_set` without recomputing.
 */
export type ParticipantSelf = { user_id: string, cap_set: number, joined_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The full summary of a room that the server can publish. The
 * `participants` list includes the host; `host_disconnected`
 * and `host_disconnect_deadline_ms` describe the host's
 * transport state when migration is on.
 */
export type RoomSummary = { id: string, code: string, title: string, host_user_id: string, host_migration_enabled: boolean, created_ms: bigint, participants: Array<Participant>, host_disconnected: boolean, host_disconnect_deadline_ms: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The view of a single participant published to other
 * participants. Carries the pubkey so other clients can verify
 * signed messages from that participant (P3+ playback
 * commands).
 */
export type Participant = { user_id: string, pubkey: Array<number>, display_name: string, joined_ms: bigint, status: ParticipantStatus, last_seen_ms: bigint, is_host: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Participant transport status. `Joining` is the brief moment
 * after ROOM_JOIN_REQUEST before the first inbound message;
 * `Connected` is the steady state; `Reconnecting` is set when
 * the participant's transport was lost and the server is
 * waiting for a re-handshake; `Disconnected` is the terminal
 * state for a transport loss that did not recover; `Left` is
 * the terminal state for an intentional ROOM_LEAVE.
 */
export type ParticipantStatus = "Joining" | "Connected" | "Reconnecting" | "Disconnected" | "Left";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PARTICIPANT_JOINED (S -> C). Broadcast when a new participant
 * enters the room.
 */
export type ParticipantJoinedPayload = { participant: Participant, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PARTICIPANT_LEFT (S -> C). Broadcast when a participant
 * leaves for any reason.
 */
export type ParticipantLeftPayload = { user_id: string, 
/**
 * `"leave"` | `"timeout"` | `"kick"` | `"host_migrated_away"`.
 * The v1 protocol does not define a `kick`; the value is
 * reserved for a future admin command. `host_migrated_away`
 * is broadcast when the host's transport was lost and the
 * new host was elected, so clients that had marked the old
 * host as `Reconnecting` can update the participant list.
 */
reason: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_DISCONNECTED (S -> C). Sent to all participants when
 * the host's transport is lost. `new_host_user_id` is `Some`
 * only when migration just happened (i.e. the grace period
 * elapsed); during the grace it is `None` and the deadline
 * tells the client when the migration will occur.
 */
export type HostDisconnectedPayload = { previous_host_user_id: string, reconnect_deadline_ms: bigint, new_host_user_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_RECONNECTED (S -> C). Sent when the host re-auths
 * before the grace period elapses.
 */
export type HostReconnectedPayload = { host_user_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_MIGRATED (S -> C). Sent when a new host was elected.
 * The old host is now a normal viewer.
 *
 * `summary` carries the authoritative post-migration room
 * snapshot. Clients should replace their cached state with
 * it on receipt; if it is `None` (older server build) the
 * client falls back to the pre-P2-T05 behavior of just
 * updating `host_user_id` and clearing the grace flag.
 */
export type HostMigratedPayload = { previous_host_user_id: string, new_host_user_id: string, summary?: RoomSummary | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CLOSED (S -> C). The room has ended.
 */
export type RoomClosedPayload = { 
/**
 * `"host_left"` | `"host_disconnected_no_migration"` |
 * `"admin"` | `"empty"`. v1 only emits the first two;
 * the others are reserved for future tasks.
 */
reason: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_ERROR (S -> C). Sent in response to a malformed or
 * out-of-state ROOM_* envelope.
 */
export type RoomErrorPayload = { code: "Unauthorized" | "InvalidCode" | "RoomNotFound" | "RoomClosed" | "RoomFull" | "AlreadyJoined" | "NotJoined" | "InvalidState" | "NotHost" | "MigrationDisabled" | "Internal", message: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed set of room-error codes. The wire representation
 * is the discriminator name; the integer in the comment is the
 * v1 stable identifier (kept here for spec cross-referencing
 * only; the protocol itself does not transmit it).
 */
export type RoomErrorCode = "Unauthorized" | "InvalidCode" | "RoomNotFound" | "RoomClosed" | "RoomFull" | "AlreadyJoined" | "NotJoined" | "InvalidState" | "NotHost" | "MigrationDisabled" | "Internal";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PRESENCE (C -> S). The client periodically re-sends a
 * PRESENCE envelope to refresh its `last_seen` timestamp. The
 * payload is a single `status: "alive"` field in v1; the
 * status string is reserved for a future "afk" / "do not
 * disturb" extension.
 */
export type PresencePayload = { status: string, };

