// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Example payload used to smoke-test the `ts-rs` generator in P0-T07.
 *
 * This is deliberately a toy struct, not a real protocol envelope. The
 * shape exercises the bits the generator needs to round-trip:
 *
 * - a `String` (`id`) to exercise string marshalling
 * - an integer (`counter`) to exercise numeric marshalling
 * - an `Option<String>` (`note`) to exercise nullable fields
 * - a nested `enum` (`mood`) to exercise tagged-union marshalling
 *
 * `mood` is marked `#[ts(inline)]` so the `Mood` union is rendered inline
 * in `HelloWorld` and the generated `ts/index.ts` stays self-contained
 * (no `import { Mood } from "../Mood"` line). Real envelope types in P3+
 * will be free to either inline or import; this is a smoke test of the
 * generator, not a fixed design decision.
 *
 * Real envelope types land in P3+ per `docs/ARCHITECTURE.md` section 18.3.
 */
export type HelloWorld = { id: string, counter: number, note: string | null, mood: "Happy" | "Neutral" | "Sad", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Mood = "Happy" | "Neutral" | "Sad";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire envelope for every message. See §18.3.
 */
export type Envelope = { 
/**
 * Protocol version. Always `1` for v1; receivers reject
 * anything else (§18.11).
 */
v: number, 
/**
 * The message type. See [`MessageKind`]. Wire field is
 * `type`; we use a Rust field name that does not collide
 * with the reserved keyword.
 */
type: MessageKind, 
/**
 * Unique per-message UUID v7. The idempotency key for
 * server-side dedup (§18.7).
 */
id: string, 
/**
 * `None` for handshake messages; `Some(room_id)` otherwise.
 */
room_id: string | null, 
/**
 * `None` for handshake and server-originated messages.
 */
sender: Sender | null, 
/**
 * Sender wall clock at send (unix ms). Informational;
 * replay protection is by `seq` (§18.7).
 */
ts_ms: bigint, 
/**
 * Monotonic per-sender sequence. First message after
 * connect is `1`; never reused.
 */
seq: bigint, 
/**
 * Type-specific payload. Held as a generic JSON value so
 * the envelope is schema-agnostic.
 */
payload: unknown, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The message type tag. Wire field is `type`. The v1 spec only
 * defines a handful of types; future types (P3+ room lifecycle,
 * playback, drawing, etc.) will be added as new variants.
 */
export type MessageKind = "HELLO" | "WELCOME" | "CHALLENGE" | "AUTH" | "AUTH_OK" | "AUTH_FAIL" | "ROOM_CREATE" | "ROOM_CREATED" | "ROOM_JOIN_REQUEST" | "ROOM_JOINED" | "ROOM_LEAVE" | "ROOM_STATE" | "PARTICIPANT_JOINED" | "PARTICIPANT_LEFT" | "HOST_DISCONNECTED" | "HOST_RECONNECTED" | "HOST_MIGRATED" | "ROOM_CLOSED" | "ROOM_ERROR" | "PRESENCE" | "RATE_LIMIT" | "MANIFEST_PUBLISH" | "MANIFEST_PUBLISHED" | "MANIFEST_REQUEST" | "MANIFEST_RESPONSE" | "SIGNAL" | "PLAYBACK_CMD" | "POSITION_REPORT" | "SKEW_PROBE" | "SKEW_REPLY";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The per-envelope sender identity. The signature is over the
 * canonicalized payload bytes (§18.9). The sender is `None` for
 * handshake messages and server-originated broadcasts.
 */
export type Sender = { 
/**
 * Server-assigned UUID v7 (architecture §20.4.4). The
 * client-side `user_id` (sha256 hex) is NOT used here.
 */
user_id: string, 
/**
 * 32-byte Ed25519 public key.
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the canonical payload
 * (or, for AUTH, over the raw 32-byte nonce).
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HELLO (C -> S).
 */
export type HelloPayload = { client_version: string, platform: "win" | "mac" | "linux", device_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WELCOME (S -> C).
 */
export type WelcomePayload = { session_id: string, server_ts_ms: bigint, config: WelcomeConfig, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-published session configuration.
 */
export type WelcomeConfig = { max_room_size: number, rate: WelcomeRate, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-connection rate limits announced at WELCOME.
 */
export type WelcomeRate = { msgs_per_sec: number, bytes_per_sec: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CHALLENGE (S -> C).
 */
export type ChallengePayload = { 
/**
 * 32-byte random nonce. The client signs this raw (no
 * domain tag, §20.4.4) and returns the signature in
 * [`AuthPayload::sig`].
 */
nonce: Array<number>, 
/**
 * Server-side absolute expiry (unix ms).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH (C -> S).
 */
export type AuthPayload = { 
/**
 * 32-byte Ed25519 public key. The server uses this as the
 * canonical identifier for the user (§21.3).
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the raw 32-byte nonce
 * from the preceding CHALLENGE.
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_OK (S -> C).
 */
export type AuthOkPayload = { 
/**
 * Server-assigned UUID v7 (§20.4.4). NOT the client's
 * sha256-hex `user_id`.
 */
user_id: string, bearer: AuthBearer, 
/**
 * The 32-byte public key the server associated with the
 * user. Echoes the value the client sent in AUTH so the
 * client can confirm the binding.
 */
pubkey: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bearer token issued by the server on successful AUTH.
 */
export type AuthBearer = { 
/**
 * 32-byte bearer token. The client holds the plaintext
 * only in memory; the server stores sha256(token) in
 * SQLite (§21.3).
 */
token: Array<number>, 
/**
 * Absolute expiry (unix ms). 15 minutes by default (§20.4.4).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_FAIL (S -> C).
 */
export type AuthFailPayload = { reason: "bad_sig" | "expired" | "banned" | "rate", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failure reason for an AUTH_FAIL.
 */
export type AuthFailReason = "bad_sig" | "expired" | "banned" | "rate";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scope of a rate-limit hit. v1 only emits `Conn`; the
 * `Room` and `Ip` variants are reserved for future tasks
 * and intentionally NOT implemented in P2-T07 (per the
 * spec's hard-scope rules).
 */
export type RateLimitScope = "conn";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RATE_LIMIT (S -> C). Sent in response to a post-handshake
 * frame that exhausted the per-connection msg/s or
 * bytes/s token bucket. The handshake path continues to
 * emit `AUTH_FAIL(Rate)` per §20.8; RATE_LIMIT is the
 * structured post-handshake equivalent.
 *
 * `retry_after_ms` is the server's hint to the client for
 * when it can resume sending. v1 always advertises
 * 1 000 ms (the throttle window).
 *
 * `observed` is the rate the offender was trying to
 * consume (msg-count or bytes-count depending on which
 * bucket missed). `limit` is the configured ceiling.
 */
export type RateLimitPayload = { scope: "conn", retry_after_ms: number, observed: number, limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The client OS. v1 supports win, mac, linux.
 */
export type Platform = "win" | "mac" | "linux";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CREATE (C -> S). The creator chooses the migration
 * setting at creation; the v1 protocol does not let it be
 * changed later.
 */
export type RoomCreatePayload = { title: string, migration_enabled: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CREATED (S -> C). Server's response to a successful
 * ROOM_CREATE. Includes the room summary and the caller's own
 * participant record.
 */
export type RoomCreatedPayload = { room: RoomSummary, you: ParticipantSelf, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_JOIN_REQUEST (C -> S). The 6-char code is uppercase; the
 * display name is 1-32 chars and validated by the server.
 */
export type RoomJoinRequestPayload = { code: string, display_name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_JOINED (S -> C). Server's response to a successful
 * ROOM_JOIN_REQUEST.
 */
export type RoomJoinedPayload = { room: RoomSummary, you: ParticipantSelf, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_LEAVE (C -> S). Intentional leave. The payload is
 * empty in v1; the server reads the authenticated user_id off
 * the bearer.
 */
export type RoomLeavePayload = Record<symbol, never>;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_STATE (S -> C). Full snapshot of a room.
 */
export type RoomStatePayload = { room: RoomSummary, 
/**
 * When the host transport has been lost and the room has
 * migration enabled, this is the unix-ms deadline after
 * which the server will elect a new host. `None` when the
 * host is connected.
 */
host_disconnect_deadline_ms: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The caller's own view of themselves in a room. Echoed in
 * `ROOM_CREATED` / `ROOM_JOINED` so the client can show the
 * right `joined_ms` / `cap_set` without recomputing.
 */
export type ParticipantSelf = { user_id: string, cap_set: number, joined_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The full summary of a room that the server can publish. The
 * `participants` list includes the host; `host_disconnected`
 * and `host_disconnect_deadline_ms` describe the host's
 * transport state when migration is on.
 */
export type RoomSummary = { id: string, code: string, title: string, host_user_id: string, host_migration_enabled: boolean, created_ms: bigint, participants: Array<Participant>, host_disconnected: boolean, host_disconnect_deadline_ms: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The view of a single participant published to other
 * participants. Carries the pubkey so other clients can verify
 * signed messages from that participant (P3+ playback
 * commands).
 */
export type Participant = { user_id: string, pubkey: Array<number>, display_name: string, joined_ms: bigint, status: ParticipantStatus, last_seen_ms: bigint, is_host: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Participant transport status. `Joining` is the brief moment
 * after ROOM_JOIN_REQUEST before the first inbound message;
 * `Connected` is the steady state; `Reconnecting` is set when
 * the participant's transport was lost and the server is
 * waiting for a re-handshake; `Disconnected` is the terminal
 * state for a transport loss that did not recover; `Left` is
 * the terminal state for an intentional ROOM_LEAVE.
 */
export type ParticipantStatus = "Joining" | "Connected" | "Reconnecting" | "Disconnected" | "Left";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PARTICIPANT_JOINED (S -> C). Broadcast when a new participant
 * enters the room.
 */
export type ParticipantJoinedPayload = { participant: Participant, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PARTICIPANT_LEFT (S -> C). Broadcast when a participant
 * leaves for any reason.
 */
export type ParticipantLeftPayload = { user_id: string, 
/**
 * `"leave"` | `"timeout"` | `"kick"` | `"host_migrated_away"`.
 * The v1 protocol does not define a `kick`; the value is
 * reserved for a future admin command. `host_migrated_away`
 * is broadcast when the host's transport was lost and the
 * new host was elected, so clients that had marked the old
 * host as `Reconnecting` can update the participant list.
 */
reason: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_DISCONNECTED (S -> C). Sent to all participants when
 * the host's transport is lost. `new_host_user_id` is `Some`
 * only when migration just happened (i.e. the grace period
 * elapsed); during the grace it is `None` and the deadline
 * tells the client when the migration will occur.
 */
export type HostDisconnectedPayload = { previous_host_user_id: string, reconnect_deadline_ms: bigint, new_host_user_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_RECONNECTED (S -> C). Sent when the host re-auths
 * before the grace period elapses.
 */
export type HostReconnectedPayload = { host_user_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HOST_MIGRATED (S -> C). Sent when a new host was elected.
 * The old host is now a normal viewer.
 *
 * `summary` carries the authoritative post-migration room
 * snapshot. Clients should replace their cached state with
 * it on receipt; if it is `None` (older server build) the
 * client falls back to the pre-P2-T05 behavior of just
 * updating `host_user_id` and clearing the grace flag.
 */
export type HostMigratedPayload = { previous_host_user_id: string, new_host_user_id: string, summary?: RoomSummary | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_CLOSED (S -> C). The room has ended.
 */
export type RoomClosedPayload = { 
/**
 * `"host_left"` | `"host_disconnected_no_migration"` |
 * `"admin"` | `"empty"`. v1 only emits the first two;
 * the others are reserved for future tasks.
 */
reason: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ROOM_ERROR (S -> C). Sent in response to a malformed or
 * out-of-state ROOM_* envelope.
 */
export type RoomErrorPayload = { code: "Unauthorized" | "InvalidCode" | "RoomNotFound" | "RoomClosed" | "RoomFull" | "AlreadyJoined" | "NotJoined" | "InvalidState" | "NotHost" | "MigrationDisabled" | "Internal" | "StaleCommand", message: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed set of room-error codes. The wire representation
 * is the discriminator name; the integer in the comment is the
 * v1 stable identifier (kept here for spec cross-referencing
 * only; the protocol itself does not transmit it).
 */
export type RoomErrorCode = "Unauthorized" | "InvalidCode" | "RoomNotFound" | "RoomClosed" | "RoomFull" | "AlreadyJoined" | "NotJoined" | "InvalidState" | "NotHost" | "MigrationDisabled" | "Internal" | "StaleCommand";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PRESENCE (C -> S). The client periodically re-sends a
 * PRESENCE envelope to refresh its `last_seen` timestamp. The
 * payload is a single `status: "alive"` field in v1; the
 * status string is reserved for a future "afk" / "do not
 * disturb" extension.
 */
export type PresencePayload = { status: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MANIFEST_PUBLISH (C -> S, host -> server). The host signs
 * a fresh [`locast_manifest::MediaManifest`] and submits it
 * to the server for broadcast. The server is the relay; it
 * does NOT validate beyond the bearer + the `PublishManifest`
 * capability check (host-only at the time of publish).
 */
export type ManifestPublishPayload = { 
/**
 * The signed manifest. The server-side defense-in-depth
 * check is a `locast_manifest::verify_manifest` call, but
 * it is NOT the trust boundary: the viewer's TOFU check
 * against the invite's `h=` parameter is.
 */
manifest: MediaManifest, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MANIFEST_PUBLISHED (S -> C, server -> all participants).
 * Broadcast to every participant in the room after a
 * successful MANIFEST_PUBLISH. Viewers store the verified
 * manifest locally and kick off the P3 download flow.
 */
export type ManifestPublishedPayload = { 
/**
 * The signed manifest, echoed from the host's
 * MANIFEST_PUBLISH. Viewers verify the signature against
 * the host's pubkey (the manifest's
 * `host_signature.public_key`) and TOFU-compare against
 * the invite's `h=` parameter.
 */
manifest: MediaManifest, 
/**
 * Server-assigned per-room monotonic version. `1` on
 * the first publish of a room; incremented on each
 * subsequent publish. Viewers persist this in
 * `room_manifests.version` and use it to ignore
 * out-of-order `MANIFEST_PUBLISHED` envelopes.
 */
version: bigint, 
/**
 * Server-stamped publication time, unix ms. The viewer
 * uses this as the row's `created_at` for the local
 * `room_manifests` table.
 */
published_at_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MANIFEST_REQUEST (C -> S, any room member -> server).
 * A late-joiner catch-up request: the server replies with
 * `MANIFEST_RESPONSE` carrying the room's currently-
 * authoritative manifest (highest `version` in the
 * `room_manifests` table). The request is a no-op if no
 * manifest has been published yet.
 *
 * The `media_id` field is informational (architecture
 * §18.4.3). P3-T04's planner will filter the returned
 * `manifest.media[]` by `media_id` if it is present; in
 * v1 the request asks for the full manifest and the
 * client does the filtering.
 */
export type ManifestRequestPayload = { media_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MANIFEST_RESPONSE (S -> C). The server's reply to a
 * MANIFEST_REQUEST. The payload mirrors the MANIFEST_PUBLISHED
 * payload (the manifest, the version, the publish time).
 */
export type ManifestResponsePayload = { 
/**
 * The signed manifest, identical to what a
 * MANIFEST_PUBLISHED would have carried at this
 * `version`.
 */
manifest: MediaManifest, 
/**
 * Server-assigned per-room monotonic version.
 */
version: bigint, 
/**
 * Server-stamped publication time, unix ms.
 */
published_at_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SIGNAL (C -> S -> C). WebRTC SDP/ICE relay between two room
 * members. The server is a pure relay: it routes the envelope
 * from `sender` to `to_user_id` without inspecting the `sdp` or
 * `candidates` bodies (docs/ARCHITECTURE.md §19.3.3, §18.5.1).
 *
 * The wire carries three discriminated payloads via the
 * `kind` field:
 * - `Offer`: an SDP offer (`sdp` is set, `candidates` is None
 *   at offer time; trickle candidates come in later `Ice`
 *   envelopes).
 * - `Answer`: an SDP answer (`sdp` is set).
 * - `Ice`: a single ICE candidate (`candidates` carries one
 *   entry); the server forwards it unchanged. A `candidates`
 *   list of length 1 with an empty-string `candidate` field
 *   signals `end-of-candidates` per §19.3.3.
 *
 * All three variants carry an Ed25519 signature in
 * `envelope.sender.sig` over the canonicalized payload bytes
 * (domain-separated by `locast/v1/SIGNAL`); the server
 * verifies the signature against the sender's pubkey and
 * rejects envelopes whose `sender` is missing or whose
 * `sender.user_id` / `sender.pubkey` do not match the
 * bearer-derived identity (P3-T05 security model).
 *
 * The `sdp` blob is base64 NOT encoded: it is the raw SDP
 * text. The application-layer cap is 64 KiB per envelope
 * (enforced server-side, not here).
 */
export type SignalPayload = { 
/**
 * Target peer (the receiving user_id).
 */
to_user_id: string, 
/**
 * Which kind of signal this is.
 */
kind: SignalKind, 
/**
 * SDP body for Offer / Answer; None for Ice.
 * Raw SDP text (not base64).
 */
sdp?: string | null, 
/**
 * Single ICE candidate for Ice; None for Offer / Answer.
 * The candidate string is the SDP `candidate:` attribute
 * value (without the leading `candidate:` prefix is also
 * acceptable; the server is a pure relay and does not
 * inspect the body). An empty `candidate` signals
 * `end-of-candidates`.
 */
candidates?: Array<SignalCandidate> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The discriminated kind inside a SIGNAL envelope.
 */
export type SignalKind = "offer" | "answer" | "ice";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single ICE candidate entry inside a SIGNAL Ice envelope.
 */
export type SignalCandidate = { 
/**
 * The candidate string (SDP `candidate:<...>` value, or
 * the full line including the `candidate:` prefix). The
 * server does not parse this; it is forwarded verbatim.
 */
candidate: string, 
/**
 * The `sdpMid` of the candidate (typically `"0"`). The
 * server does not inspect this; it is forwarded verbatim.
 */
sdp_mid?: string | null, 
/**
 * the `sdpMLineIndex` of the candidate. The server does
 * not inspect this; it is forwarded verbatim.
 */
sdp_m_line_index?: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PLAYBACK_CMD (C -> S, S -> all).
 *
 * The single envelope kind for playback control. The
 * discriminant is `action`. The server stamps `server_seq` and
 * `server_ts_ms` on the rebroadcast payload; the original
 * sender-side payload carries only the per-sender
 * `monotonic_seq` and the playback fields.
 */
export type PlaybackCommandPayload = { 
/**
 * Discriminant: which playback action this command
 * represents.
 */
type: PlaybackAction, 
/**
 * Per-sender monotonic sequence. Must be exactly
 * `last_acked_seq[sender_id] + 1` per docs/ARCHITECTURE.md
 * §13.2. `monotonic_seq <= last_acked_seq[sender_id]` is
 * dropped as a duplicate; `monotonic_seq >
 * last_acked_seq[sender_id] + 1` is rejected as a gap.
 */
monotonic_seq: bigint, 
/**
 * Media position the command applies to (PLAY/SEEK).
 * Always present; ignored for PAUSE (the room's last PLAY /
 * SEEK position remains authoritative).
 */
media_position_ms: bigint, 
/**
 * Sender's wall clock at send (unix ms). Informational
 * only; the server stamps its own `server_ts_ms` on
 * acceptance.
 */
client_ts_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The discriminated playback action.
 *
 * §13.4 defines `PLAY`, `PAUSE`, `SEEK` as the v1 action set.
 * We send the discriminant as `"play" | "pause" | "seek"` so
 * the wire shape stays stable if a future task adds more
 * actions.
 */
export type PlaybackAction = "play" | "pause" | "seek";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PLAYBACK_CMD (S -> all). The rebroadcast payload after the
 * server has accepted a command. The per-sender `monotonic_seq`
 * is preserved; the server stamps `server_seq` and
 * `server_ts_ms`.
 */
export type PlaybackAcceptedEvent = { 
/**
 * Original sender's user_id. Mirrors §13.1 PLAY's
 * `sender_id` field; the per-room broadcast carries it so
 * the receiving client can drop late commands
 * (docs/ARCHITECTURE.md §13.2).
 */
sender_id: string, 
/**
 * The action that was accepted.
 */
action: PlaybackAction, 
/**
 * Sender's monotonic_seq (verbatim from the command).
 */
monotonic_seq: bigint, 
/**
 * Media position the command applies to. Always present;
 * ignored for PAUSE.
 */
media_position_ms: bigint, 
/**
 * Sender's wall clock at send (verbatim from the command).
 */
client_ts_ms: bigint, 
/**
 * Per-room server-assigned monotonic sequence. First
 * accepted command after room creation is `1`; increments
 * strictly per accepted command. NOT incremented for
 * rejected commands.
 */
server_seq: bigint, 
/**
 * Server-stamped wall clock at acceptance, unix ms.
 */
server_ts_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POSITION_REPORT (C -> S -> other room members).
 *
 * 1 Hz non-authoritative snapshot of the sender's local
 * playback state. The server is a pure relay: it does NOT
 * validate the playback position (no bounds check against
 * media duration; that is the host's job at PUBLISH time).
 * The server only validates that the sender is currently a
 * member of the named room and forwards the payload
 * verbatim. See module docs above for the architecture
 * references.
 */
export type PositionReportPayload = { 
/**
 * Originating participant's `user_id`. Set by the
 * server from the validated bearer so the receiver
 * can attribute the report to a sender without
 * trusting an unverified client field. The wire
 * shape mirrors architecture §13.1 (the JSON
 * example includes `user_id`).
 */
user_id: string, 
/**
 * Local `<video>` position in milliseconds (rounded from
 * the floating-point `currentTime` seconds). The wire
 * unit is integer ms so the server can re-emit the
 * value verbatim without precision drift. `0` is a
 * valid value (the very first frame); negative values
 * are not produced by any conforming client.
 */
media_position_ms: bigint, 
/**
 * `true` when the local `<video>.paused === false` (i.e.
 * the media element is actively playing); `false` when
 * the element is paused. `playing` is observed locally
 * and is not asserted by the server.
 */
playing: boolean, 
/**
 * Sender's wall clock at send (unix ms). Informational
 * only; the server does not stamp `server_ts_ms` on the
 * rebroadcast (the roadmap explicitly says "server
 * forwards without modification"). Receivers may use
 * this for display only.
 */
client_ts_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level Locast media manifest.
 */
export type MediaManifest = { 
/**
 * Manifest schema version. Currently 1.
 */
manifest_version: number, 
/**
 * Room identifier (UUIDv4 in v1).
 */
room_id: string, 
/**
 * Media items in the room. May be empty in principle; the viewer
 * decides what "empty" means for its UI.
 */
media: Array<MediaEntry>, 
/**
 * Subtitle tracks. May be empty; serializes as `[]`.
 */
subtitles: Array<SubtitleEntry>, 
/**
 * Creation timestamp as Unix milliseconds. Display only; not part
 * of the signed payload's identity contract.
 */
created_at: bigint, 
/**
 * Host signature. The canonicalizer always replaces this field's
 * value with `null`; the data model retains whatever the host set.
 */
host_signature: HostSignature | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A media entry inside a manifest's `media` array.
 */
export type MediaEntry = { 
/**
 * Stable identifier for this media item (UUIDv4 in v1).
 */
id: string, 
/**
 * File name as it appears in the source tree.
 */
filename: string, 
/**
 * SHA-256 of the file's full contents, 64 lowercase hex chars.
 */
sha256: string, 
/**
 * BLAKE3 of the file's full contents, 64 lowercase hex chars.
 */
blake3: string, 
/**
 * File size in bytes.
 */
size_bytes: bigint, 
/**
 * MIME type.
 */
mime: string, 
/**
 * Duration in milliseconds.
 */
duration_ms: bigint, 
/**
 * Optional dimensions. Absent (not `null`) from the canonical JSON
 * when `None`.
 */
dimensions?: Dimensions | null, 
/**
 * Optional codec metadata. Absent (not `null`) from the canonical
 * JSON when `None`.
 */
codecs?: Codecs | null, 
/**
 * Ordered list of sources, host first.
 */
sources: Array<Source>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pixel dimensions. Both fields are required when the parent
 * `Dimensions` value is present.
 */
export type Dimensions = { width: number, height: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Codec metadata for a media entry. Each component is optional so the
 * caller can describe audio-only, video-only, or container-only streams.
 */
export type Codecs = { video?: string | null, audio?: string | null, container?: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A download source. The host is always the first entry in v1.
 */
export type Source = { 
/**
 * Peer identifier. Either a base64 Ed25519 public key or a
 * `sha256:` hex prefix; the canonicalizer does not normalize
 * between these two representations.
 */
peer_id: string, 
/**
 * URL hint. v1 always emits `null` here.
 */
url_hint: string | null, 
/**
 * 0 means "preferred". Higher numbers are deprioritized.
 */
priority: number, 
/**
 * Chunk size in bytes.
 */
chunk_size: number, 
/**
 * Number of chunks. Equal to `chunk_hashes.len()`.
 */
total_chunks: number, 
/**
 * Per-chunk SHA-256 hashes, one per chunk, in order.
 */
chunk_hashes: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subtitle entry. The `sources` field uses the same `Source` shape
 * as `MediaEntry`.
 */
export type SubtitleEntry = { id: string, 
/**
 * BCP-47 language tag.
 */
language: string, 
/**
 * Human-readable label.
 */
label: string, filename: string, 
/**
 * SHA-256 of the file's full contents, 64 lowercase hex chars.
 */
sha256: string, 
/**
 * File size in bytes.
 */
size_bytes: bigint, 
/**
 * Subtitle codec, one of `srt`, `ass`, `ssa`, `vtt`, `webvtt`.
 */
codec: string, sources: Array<Source>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host signature block. Present on the wire at runtime; the
 * canonicalizer always strips the actual value and emits `null` in the
 * canonical bytes regardless of what the data model holds.
 */
export type HostSignature = { 
/**
 * Public key identifier.
 */
public_key: string, 
/**
 * Signature algorithm name (e.g. `ed25519`).
 */
algorithm: string, 
/**
 * Signature value, base64 or hex encoded depending on algorithm.
 */
value: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SKEW_REPLY-side NTP sample (architecture section 13.3).
 * The client reconstructs the four-timestamp exchange from
 * its own local clock at send (t0_local_ms) and at receive
 * (t3_local_ms) plus the server's server_ts_ms from the
 * reply payload. The client_send_ms_echo is included so
 * the client can assert the round trip was not reordered.
 */
export type SkewSample = { t0_local_ms: bigint, t3_local_ms: bigint, server_ts_ms: bigint, client_send_ms_echo: bigint, };