// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Example payload used to smoke-test the `ts-rs` generator in P0-T07.
 *
 * This is deliberately a toy struct, not a real protocol envelope. The
 * shape exercises the bits the generator needs to round-trip:
 *
 * - a `String` (`id`) to exercise string marshalling
 * - an integer (`counter`) to exercise numeric marshalling
 * - an `Option<String>` (`note`) to exercise nullable fields
 * - a nested `enum` (`mood`) to exercise tagged-union marshalling
 *
 * `mood` is marked `#[ts(inline)]` so the `Mood` union is rendered inline
 * in `HelloWorld` and the generated `ts/index.ts` stays self-contained
 * (no `import { Mood } from "../Mood"` line). Real envelope types in P3+
 * will be free to either inline or import; this is a smoke test of the
 * generator, not a fixed design decision.
 *
 * Real envelope types land in P3+ per `docs/ARCHITECTURE.md` section 18.3.
 */
export type HelloWorld = { id: string, counter: number, note: string | null, mood: "Happy" | "Neutral" | "Sad", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Mood = "Happy" | "Neutral" | "Sad";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire envelope for every message. See §18.3.
 */
export type Envelope = { 
/**
 * Protocol version. Always `1` for v1; receivers reject
 * anything else (§18.11).
 */
v: number, 
/**
 * The message type. See [`MessageKind`]. Wire field is
 * `type`; we use a Rust field name that does not collide
 * with the reserved keyword.
 */
type: MessageKind, 
/**
 * Unique per-message UUID v7. The idempotency key for
 * server-side dedup (§18.7).
 */
id: string, 
/**
 * `None` for handshake messages; `Some(room_id)` otherwise.
 */
room_id: string | null, 
/**
 * `None` for handshake and server-originated messages.
 */
sender: Sender | null, 
/**
 * Sender wall clock at send (unix ms). Informational;
 * replay protection is by `seq` (§18.7).
 */
ts_ms: bigint, 
/**
 * Monotonic per-sender sequence. First message after
 * connect is `1`; never reused.
 */
seq: bigint, 
/**
 * Type-specific payload. Held as a generic JSON value so
 * the envelope is schema-agnostic.
 */
payload: unknown, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The message type tag. Wire field is `type`. The v1 spec only
 * defines a handful of types; future types (P3+ room lifecycle,
 * playback, drawing, etc.) will be added as new variants.
 */
export type MessageKind = "HELLO" | "WELCOME" | "CHALLENGE" | "AUTH" | "AUTH_OK" | "AUTH_FAIL";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The per-envelope sender identity. The signature is over the
 * canonicalized payload bytes (§18.9). The sender is `None` for
 * handshake messages and server-originated broadcasts.
 */
export type Sender = { 
/**
 * Server-assigned UUID v7 (architecture §20.4.4). The
 * client-side `user_id` (sha256 hex) is NOT used here.
 */
user_id: string, 
/**
 * 32-byte Ed25519 public key.
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the canonical payload
 * (or, for AUTH, over the raw 32-byte nonce).
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HELLO (C -> S).
 */
export type HelloPayload = { client_version: string, platform: "win" | "mac" | "linux", device_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WELCOME (S -> C).
 */
export type WelcomePayload = { session_id: string, server_ts_ms: bigint, config: WelcomeConfig, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-published session configuration.
 */
export type WelcomeConfig = { max_room_size: number, rate: WelcomeRate, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-connection rate limits announced at WELCOME.
 */
export type WelcomeRate = { msgs_per_sec: number, bytes_per_sec: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CHALLENGE (S -> C).
 */
export type ChallengePayload = { 
/**
 * 32-byte random nonce. The client signs this raw (no
 * domain tag, §20.4.4) and returns the signature in
 * [`AuthPayload::sig`].
 */
nonce: Array<number>, 
/**
 * Server-side absolute expiry (unix ms).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH (C -> S).
 */
export type AuthPayload = { 
/**
 * 32-byte Ed25519 public key. The server uses this as the
 * canonical identifier for the user (§21.3).
 */
pubkey: Array<number>, 
/**
 * 64-byte Ed25519 signature over the raw 32-byte nonce
 * from the preceding CHALLENGE.
 */
sig: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_OK (S -> C).
 */
export type AuthOkPayload = { 
/**
 * Server-assigned UUID v7 (§20.4.4). NOT the client's
 * sha256-hex `user_id`.
 */
user_id: string, bearer: AuthBearer, 
/**
 * The 32-byte public key the server associated with the
 * user. Echoes the value the client sent in AUTH so the
 * client can confirm the binding.
 */
pubkey: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bearer token issued by the server on successful AUTH.
 */
export type AuthBearer = { 
/**
 * 32-byte bearer token. The client holds the plaintext
 * only in memory; the server stores sha256(token) in
 * SQLite (§21.3).
 */
token: Array<number>, 
/**
 * Absolute expiry (unix ms). 15 minutes by default (§20.4.4).
 */
expires_ms: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AUTH_FAIL (S -> C).
 */
export type AuthFailPayload = { reason: "bad_sig" | "expired" | "banned" | "rate", };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failure reason for an AUTH_FAIL.
 */
export type AuthFailReason = "bad_sig" | "expired" | "banned" | "rate";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The client OS. v1 supports win, mac, linux.
 */
export type Platform = "win" | "mac" | "linux";

